name: CI Qualite de Code Pro

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
      - name: "Recupere le code"
        uses: actions/checkout@v4

      - name: "Build de l'image"
        run: docker build --build-arg PYTHON_VER=${{ matrix.python-version }} -t image-qualite .

      - name: "Etape 1 : Verification du Style (Flake8)"
        # On enlève '--select' pour activer TOUS les contrôles de style par défaut
        run: docker run image-qualite flake8 . --count --show-source --statistics

      - name: "Etape 2 : Tests Unitaires (Pytest)"
        run: docker run image-qualite pytest test_calcul.py

      